package com.ebiznext.sbt.sample.reception.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.math.BigDecimal;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

import com.ebiznext.sbt.sample.reception.wsclient.ZSMMI899RECPCMD;
import com.ebiznext.sbt.sample.reception.wsclient.ZSMMI899RECPLINE;
import com.ebiznext.sbt.sample.reception.wsclient.ZWSMMI899RECEPCMD;
import com.ebiznext.sbt.sample.reception.wsclient.ZWSMMI899RECEPCMD_Service;

import com.ebiznext.sbt.sample.reception.vo.CommandeReceptionnee;
import com.ebiznext.sbt.sample.utils.Configuration;

/**
 * This class was generated by Apache CXF 2.6.1 2012-11-02T20:43:10.425+01:00
 * Generated source version: 2.6.1
 * 
 */
public final class ReceptionReceptionnerCommandeCLient {

    private static final Logger LOGGER = Logger.getLogger(ReceptionReceptionnerCommandeCLient.class.getName());

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZWS_MM_I899_RECEP_CMD");

    private ReceptionReceptionnerCommandeCLient(){}

    public static boolean execute(String user, String password, String numeroDeCommande, String bonDeLivraison,
            CommandeReceptionnee[] postes) throws java.lang.Exception {
        URL wsdlURL = Configuration.getWSDL("edifice.wsdl.reception.ReceptionnerCommande");
        ZWSMMI899RECEPCMD_Service ss = new ZWSMMI899RECEPCMD_Service(wsdlURL, SERVICE_NAME);
        ZWSMMI899RECEPCMD port = ss.getZWSMMI899RECEPCMD();

        {
            ((BindingProvider) port).getRequestContext().put(BindingProvider.USERNAME_PROPERTY, user);
            ((BindingProvider) port).getRequestContext().put(BindingProvider.PASSWORD_PROPERTY, password);

            LOGGER.info("Invoking zMMI899RECEPCMD...");
            com.ebiznext.sbt.sample.reception.wsclient.ZSMMI899RECPCMD _zMMI899RECEPCMD_iCOMMANDE = new ZSMMI899RECPCMD();
            com.ebiznext.sbt.sample.reception.wsclient.ZTMMI899RECPLINE items = new com.ebiznext.sbt.sample.reception.wsclient.ZTMMI899RECPLINE();
            for (CommandeReceptionnee poste : postes) {
                ZSMMI899RECPLINE item = new ZSMMI899RECPLINE();
                item.setEBELP(poste.getNumeroLigne() +"");
                item.setMENGE(new BigDecimal(poste.getQuantite()));
                //item.setMEINS(poste.)
                items.getItem().add(item);
            }
            _zMMI899RECEPCMD_iCOMMANDE.setCOMMANDE(items);
            _zMMI899RECEPCMD_iCOMMANDE.setEBELN(numeroDeCommande);
            _zMMI899RECEPCMD_iCOMMANDE.setLFSNR(bonDeLivraison);
            javax.xml.ws.Holder<com.ebiznext.sbt.sample.reception.wsclient.BAPIRET2T> _zMMI899RECEPCMD_eMSGRETURN = new javax.xml.ws.Holder<com.ebiznext.sbt.sample.reception.wsclient.BAPIRET2T>();
            javax.xml.ws.Holder<java.lang.String> _zMMI899RECEPCMD_eRESULTAT = new javax.xml.ws.Holder<java.lang.String>();
            port.zMMI899RECEPCMD(_zMMI899RECEPCMD_iCOMMANDE, _zMMI899RECEPCMD_eMSGRETURN, _zMMI899RECEPCMD_eRESULTAT);

            LOGGER.info("zMMI899RECEPCMD._zMMI899RECEPCMD_eMSGRETURN=" + _zMMI899RECEPCMD_eMSGRETURN.value);
            LOGGER.info("zMMI899RECEPCMD._zMMI899RECEPCMD_eRESULTAT=" + _zMMI899RECEPCMD_eRESULTAT.value);
            return _zMMI899RECEPCMD_eRESULTAT.value.equals("1");
        }

    }
}
